### ISSUE TITLE
How is the 'wait' argument's value decided?

### ISSUE THREAD

**Issue by hhk998402** [xieqihui/pandas-multiprocess#7]
If my computation takes longer than 0.01 seconds, what do I do? Is there a way of automating that parameter's value based on the computation that is supposed to performed?

**Comment by xieqihui** [comment]
Hi, in fact, the `wait` argument is not necessary for your actual use. It is added in the example to demonstrate the capability of `pandas-multiprocess` to process computational expensive operations efficiently, i.e., the 'wait' time mimics the computation time of your actual operation of 'func'. So you should definitely remove it in your actual functions.

**Comment by xieqihui** [comment]
I have updated the README. Hope it explains more clearly. 
https://github.com/xieqihui/pandas-multiprocess/blob/master/README.md
